name: "Python CI"
on:

  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:

  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build docker rabbit network
        run: docker network create rabbit
      - name: Build docker container
        run: docker-compose -f docker-compose-github.yml up -d --build
      - name: Check running containers
        run: docker ps -a

  Linter:
    needs: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build docker rabbit network
        run: docker network create rabbit
      - name: Build docker container
        run: docker-compose -f docker-compose-github.yml up -d --build
      - name: Check code by linter
        run: docker exec smtp ruff check